In [ ]:
import requests
import json
import time

In [ ]:
Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJqaVeK1pJ3YARz9AXOaoNev0&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

In [ ]:
Types = []

try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=results['result']['price_level']
except:
  Price_Level=0
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Calm', 'Energetic', 'Curious/Artsy', 'Social', 'Studious', 'Sad']
MoodList = ' '.join(Moods)


Categories = ['Nature', 'Beaches', 'Wildlife', 'Gardens', 'Free', 'Views']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Hike', 'Sightseeing', 'Birdwatching', 'Swim', 'Interact with Ocean Creatures', 'Relax']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['The sea anemones, urchins, and starfish are safe to touch, but do not grab them off of the rocks, as this will injure them. ', 'Parking is free on the street.', 'To see the best views, walk along the road past the park, past the mansion, and past the sharp downward dip in the road until you reach the Sacred Cove View Trail. Take this trail down to the water and walk to the far right of the cove to view some tide pools.', 'Visit during low tide season']
InsiderTipsList =  '||'.join(InsiderTips)

In [ ]:
df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd

df0 = pd.DataFrame(df_dict)

df0.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJqaVeK1pJ3YARz9AXOaoNev0,Abalone Cove Shoreline Park,Expansive park by the ocean featuring 2 beache...,"[tourist_attraction, park, point_of_interest, ...",4.7,1508,(310) 544-5366,https://ca-ranchopalosverdes2.civicplus.com/10...,0,"5970 Palos Verdes Dr S, Rancho Palos Verdes, C...",Monday: 9:00 AM – 4:00 PM Tuesday: 9:00 AM – 4...,33.743672,-118.381423,Calm Energetic Curious/Artsy Social Studious Sad,"Nature, Beaches, Wildlife, Gardens, Free, Views","Hike, Sightseeing, Birdwatching, Swim, Interac...","The sea anemones, urchins, and starfish are sa..."

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJiXJav6K6woARGPmX6Bsp55Y&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])
Types = []

try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=results['result']['price_level']
except:
  Price_Level=0
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Calm', 'Curious/Artsy', 'Romantic', 'Sad', 'Social']
MoodList = ' '.join(Moods)
Categories = ['Beaches','Nature', 'Arts/Culture', 'Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Walk', 'Sightseeing', 'Relax', 'Sad']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['You can find free street parking in Venice Beach', 'Additionally there are many paid parking lots nearby with the closest one located at the end of Venice Boulevard']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd

df1 = pd.DataFrame(df_dict)
df1.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJiXJav6K6woARGPmX6Bsp55Y,Venice Canals,Italian-inspired artificial canals built in 19...,"[tourist_attraction, point_of_interest, establ...",4.6,9875,None,https://www.hmdb.org/m.asp?m=178246,0,"Venice, CA 90292, USA",Monday: Open 24 hours Tuesday: Open 24 hours W...,33.983503,-118.46768,Calm Curious/Artsy Romantic Sad Social,"Beaches, Nature, Arts/Culture, Free","Walk, Sightseeing, Relax, Sad",You can find free street parking in Venice Bea...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJ7YJ_IkrGwoARNak4CDihkYU&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])
Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Calm', 'Curious/Artsy', 'Studious', 'Sad','Social']
MoodList = ' '.join(Moods)
Categories = ['Bookstores','Arts/Culture', 'Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Read' , 'Take Photos','Explore Various Forms of Art/Displays', 'Relax', 'Focus' ]
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['Check out the The labyrinth tunnel. It\'s particularly popular with the Instagram crowd, where piles of books have been transformed into an art sculpture.', 'Check out the art installation where the books have taken "flight", in a scene reminiscent of a surrealist painting by Dali.', 'Take a photo through the famous peep hole.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd

###
df2 = pd.DataFrame(df_dict)
df2.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJ7YJ_IkrGwoARNak4CDihkYU,The Last Bookstore,Airy book & record store offering new & used i...,"[book_store, electronics_store, home_goods_sto...",4.7,11564,(213) 488-0599,http://www.lastbookstorela.com/,0,"453 South Spring Street Ground Floor, 121 E 5t...",Monday: 11:00 AM – 8:00 PM Tuesday: 11:00 AM –...,34.047713,-118.249828,Calm Curious/Artsy Studious Sad Social,"Bookstores, Arts/Culture, Free","Read, Take Photos, Explore Various Forms of Ar...",Check out the The labyrinth tunnel. It's parti...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJhSKS_KBU6YARVsELBhsoDi0&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])
Types = []

try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=4.9
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = "Solvang is a city in southern California's Santa Ynez Valley. It's known for its Danish-style architecture and many wineries. The Elverhøj Museum of History & Art explores the city's Danish heritage through personal stories and photographs. The Solvang Vintage Motorcycle Museum exhibits dozens of classic American, Japanese and European motorbikes. The Old Mission Santa Inés is an early-1800s Franciscan church."
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = 691
except:
  TotalReviews='None'

Moods =['Calm', 'Curious/Artsy', 'Energetic', 'Romantic', 'Shopping', 'Hungry/Thirsty', 'Sad', 'Social', 'Studious']
MoodList = ' '.join(Moods)
Categories = ['Arts/Culture', 'Wineries', 'Restaurants', 'Danish', 'Nature', 'Bars', 'Hikes', 'Walks', 'Stores']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Sightseeing' , 'Vineyards','Museums', 'Restaurants', 'Bakeries' 'Parks', 'Churches' ]
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['If you like sweets make sure to taste "Aebleskiver". It\'s a famous pastry part of Danish Culture. Solvang offers a wide variety of other pasties as well', ' Olive Oil Tasting is One of the Best Free Things to do in Solvang', 'Old Mission Santa Ines is One of the Many Great Solvang Attractions', 'The Jule Hus is One of the Best Things to See in Solvang']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd

df3 = pd.DataFrame(df_dict)
df3.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJhSKS_KBU6YARVsELBhsoDi0,Solvang,Solvang is a city in southern California's San...,"[locality, political]",4.9,691,None,http://www.cityofsolvang.com/,0,"Solvang, CA 93463, USA",None,34.59582,-120.137648,Calm Curious/Artsy Energetic Romantic Shopping...,"Arts/Culture, Wineries, Restaurants, Danish, N...","Sightseeing, Vineyards, Museums, Restaurants, ...","If you like sweets make sure to taste ""Aeblesk..."

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJE8IF_yHN3IARaEQ5vCdOgwA&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Calm', 'Curious/Artsy', 'Romatic', 'Sad', 'Social']
MoodList = ' '.join(Moods)
Categories = ['Temples & Chapels' ,'Gardens', 'Free', 'Arts/Culture']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Sightseeing' , 'Learn Hindu History','Explore Temple Grounds', 'Attend Hindu Festivals' ]
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['The BAPS Shri Swaminarayan Mandir is a popular destination for Hindus and non-Hindus alike, howver it is imoprtant to keep in mind that they have special rules in place', 'No Pets','Dress modestly. The dress code at the temple is conservative, so be sure to wear clothing that covers your shoulders and legs.', 'Remove your shoes: In many Hindu temples, visitors are expected to remove their shoes before entering the building', 'Be respectful of religious rituals: While visiting the temple, it\'s important to be respectful of the religious rituals. You may have to refrain from taking photos or videos during puja (prayer) ceremonies.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd

###
df4 = pd.DataFrame(df_dict)
df4.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJE8IF_yHN3IARaEQ5vCdOgwA,"BAPS Shri Swaminarayan Mandir, Chino Hills",Traditional Hindu temple built from Rajasthan ...,"[hindu_temple, place_of_worship, point_of_inte...",4.8,3342,(909) 614-5000,http://www.baps.org/LosAngeles,0,"15100 Fairfield Ranch Rd, Chino Hills, CA 9170...",Monday: 9:00 AM – 7:30 PM Tuesday: 9:00 AM – 7...,33.976415,-117.695549,Calm Curious/Artsy Romatic Sad Social,"Temples & Chapels, Gardens, Free, Arts/Culture","Sightseeing, Learn Hindu History, Explore Temp...",The BAPS Shri Swaminarayan Mandir is a popular...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJLYsuqGq8woARw5HvSGCXO8E&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)


Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=2
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Calm', 'Curious/Artsy', 'Romantic', 'Sad', 'Social']
MoodList = ' '.join(Moods)
Categories = ['Arts/Culture', 'Gardens', 'Nature']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Sightseeing' , 'Tennis','Libraries', 'Gardens' ]
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['Make reservations ahead of time. There are no walk in appointments unfortunately.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df5 = pd.DataFrame(df_dict)
df5.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJLYsuqGq8woARw5HvSGCXO8E,Virginia Robinson Gardens,Storied 20th-century mansion set on 6 acres of...,"[tourist_attraction, park, point_of_interest, ...",4.4,181,(310) 550-2087,http://www.robinsongardens.org/,2,"1008 Elden Way, Beverly Hills, CA 90210, USA",Monday: 9:00 AM – 4:00 PM Tuesday: 9:00 AM – 4...,34.086637,-118.417398,Calm Curious/Artsy Romantic Sad Social,"Arts/Culture, Gardens, Nature","Sightseeing, Tennis, Libraries, Gardens",Make reservations ahead of time. There are no ...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJGQN5oX2_woARuEam6IqPTmo&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=1
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Calm', 'Energetic', 'Romantic', 'Sad', 'Social']
MoodList = ' '.join(Moods)
Categories = ['Nature','Hikes', 'Views', 'Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Hikes','Sightseeing' , 'Birdwatching' ]
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['The surrounding Griffith Park area if full of other trails, hikes, parks, gardens, and the famous Griffith Observatory.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df6 = pd.DataFrame(df_dict)
df6.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJGQN5oX2_woARuEam6IqPTmo,Griffith Park Observatory Trails Peak,Hilly paths around a landmark observatory rise...,"[park, point_of_interest, establishment]",4.8,623,None,None,1,"2715 N Vermont Ave, Los Angeles, CA 90027, USA",Monday: 6:00 AM – 10:00 PM Tuesday: 6:00 AM – ...,34.128147,-118.301091,Calm Energetic Romantic Sad Social,"Nature, Hikes, Views, Free","Hikes, Sightseeing, Birdwatching",The surrounding Griffith Park area if full of ...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJa_vDely_woAR7bHQTLLrWrI&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=1
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Calm', 'Energetic', 'Romantic', 'Sad', 'Curious/Artsy']
MoodList = ' '.join(Moods)
Categories = ['Nature','Gardens', 'Views' ,'Hikes', 'Wildlife']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Walk','Sightseeing' , 'Birdwatching', 'Relax' ]
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['The surrounding Griffith Park area if full of other trails, hikes, parks, gardens, and the famous Griffith Observatory.', 'While in the area, consider checking out Fern Dell Playground (a few hundred yards away), Griffith Observatory, Bronson Caves, Funko Hollywood, Barnsdall Art Park, The Greek Theater, Vermont Canyon Play Area, and Griffith Park’s Cedar Grove.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df01 = pd.DataFrame(df_dict)
df01.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJa_vDely_woAR7bHQTLLrWrI,Fern Dell Nature Trail,"Quarter-mile footpath along a man-made stream,...","[park, tourist_attraction, point_of_interest, ...",4.8,1296,(323) 666-5046,https://www.laparks.org/griffithpark/griffith-...,1,"Fern Dell Dr, Los Angeles, CA 90027, USA",Monday: 6:00 AM – 10:00 PM Tuesday: 6:00 AM – ...,34.109385,-118.307692,Calm Energetic Romantic Sad Curious/Artsy,"Nature, Gardens, Views, Hikes, Wildlife","Walk, Sightseeing, Birdwatching, Relax",The surrounding Griffith Park area if full of ...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJvXdlhBvHwoARfS5LNYPCnEQ&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = "The Echo Park Time Travel Mart is your convenience store for time travelers. We also provide creative writing programs for students in LA. All of our programs are free and volunteer based. Proceeds from the store help support and keep our programs free."
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Curious/Artsy', 'Shopping', 'Calm', 'Energetic']
MoodList = ' '.join(Moods)
Categories = ['Non-Profit', 'Stores', 'Arts/Culture', 'Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Sightseeing' , 'Shopping', 'Donating', 'Selfies' ]
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['You can visit this place for free and look at all the cool stuff they offer']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd


###
df7 = pd.DataFrame(df_dict)
df7.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJvXdlhBvHwoARfS5LNYPCnEQ,826LA & The Echo Park Time Travel Mart,The Echo Park Time Travel Mart is your conveni...,"[tourist_attraction, point_of_interest, store,...",4.5,152,(213) 556-4861,http://www.timetravelmart.com/,0,"1714 Sunset Blvd, Los Angeles, CA 90026, USA",Monday: 12:00 – 6:00 PM Tuesday: 12:00 – 6:00 ...,34.077329,-118.259033,Curious/Artsy Shopping Calm Energetic,"Non-Profit, Stores, Arts/Culture, Free","Sightseeing, Shopping, Donating, Selfies",You can visit this place for free and look at ...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJoeH4cobAwoARtbdnxFol0VU&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Calm', 'Romantic', 'Energetic', 'Focused', 'Curious/Artsy']
MoodList = ' '.join(Moods)
Categories = ['Arts/Culture', 'Nature', 'Picnic Spots', 'Views', 'Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Hikes' , 'Sightseeing', 'Picnics', 'Explore', 'Adventure' ]
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['The surrounding Griffith Park area if full of other trails, hikes, parks, gardens, and the famous Griffith Observatory.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd

###
df8 = pd.DataFrame(df_dict)
df8.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJoeH4cobAwoARtbdnxFol0VU,Old Los Angeles Zoo,"Founded in 1912, this now-abandoned zoo offers...","[tourist_attraction, park, point_of_interest, ...",4.6,1194,(323) 913-4688,https://laparks.org/parks,0,"4801 Griffith Park Dr, Los Angeles, CA 90027, USA",Monday: 5:30 AM – 10:00 PM Tuesday: 5:30 AM – ...,34.133939,-118.289038,Calm Romantic Energetic Focused Curious/Artsy,"Arts/Culture, Nature, Picnic Spots, Views, Free","Hikes, Sightseeing, Picnics, Explore, Adventure",The surrounding Griffith Park area if full of ...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJT9Of3GeWwoARDyyechrb21w&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Calm', 'Curious/Artsy','Romantic', 'Sad', 'Social']
MoodList = ' '.join(Moods)
Categories = [ 'Arts/Culture', 'Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Walk' , 'Sightseeing', 'Photography' ]
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['The Great Wall of Los Angeles is one of Los Angeles’ true cultural landmarks and one of the country’s most respected and largest monuments to inter-racial harmony. SPARC’s first public art project and its true signature piece, the Great Wall is a landmark pictorial representation of the history of ethnic peoples of California from prehistoric times to the 1950’s, conceived by SPARC’S artistic director and founder Judy Baca.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd


###
df9 = pd.DataFrame(df_dict)
df9.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJT9Of3GeWwoARDyyechrb21w,The Great Wall of Los Angeles,"2,754-foot-long mural depicting the history of...","[tourist_attraction, point_of_interest, establ...",4.6,428,None,https://www.publicartinpublicplaces.info/the-g...,0,"12900 Oxnard St, North Hollywood, CA 91606, USA",Monday: Open 24 hours Tuesday: Open 24 hours W...,34.179236,-118.41429,Calm Curious/Artsy Romantic Sad Social,"Arts/Culture, Free","Walk, Sightseeing, Photography",The Great Wall of Los Angeles is one of Los An...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJ7wJnBuzGwoARD2vr4e0AnWU&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)


Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = "This hidden swing with a stunning hill top view is a part of Elysian Park. Elysian Park is the city's oldest public park and, at 575-acres, the second largest after Griffith Park. It is home to numerous historic sites, including the Los Angeles Police Academy and Barlow Hospital, that are linked by miles of walking trails. "

except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Calm', 'Energetic', 'Romantic', 'Social', 'Sad']
MoodList = ' '.join(Moods)
Categories = ['Arts/Culture', 'Nature',  'Hikes', 'Free', 'Picnic Spots']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Hike' , 'Sightseeing', 'Photography', 'Relax', 'Walk' ]
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['This swing is located in Elysian Park. Elysian Park also features benches, a playground, public art, various hikes and various beuatiful views.', 'Check out the Buena Vista Viewpoint also located in Elysian Park.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd

###
df10 = pd.DataFrame(df_dict)
df10.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJ7wJnBuzGwoARD2vr4e0AnWU,Secret Swing Angels Point,This hidden swing with a stunning hill top vie...,"[tourist_attraction, park, point_of_interest, ...",4.4,420,None,None,0,"Los Angeles, CA 90031, USA",Monday: 8:00 AM – 9:00 PM Tuesday: 8:00 AM – 9...,34.085344,-118.234539,Calm Energetic Romantic Social Sad,"Arts/Culture, Nature, Hikes, Free, Picnic Spots","Hike, Sightseeing, Photography, Relax, Walk",This swing is located in Elysian Park. Elysian...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJeRhEtqvHwoARn4vexuEKGnQ&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Calm', 'Romantic', 'Sad', 'Social']
MoodList = ' '.join(Moods)
Categories = ['Arts/Culture', 'Nature', 'Views', 'Free', 'Picnic Spots']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Walk' , 'Sightseeing', 'Picnics', 'Reflect' ]
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['Take the time to walk around the dusty garden trails and rocky adventure areas of this Westlake and Echo Park green space', 'The grassy central field of this park has stunning views of the Downtown skyline and a half-dozen dedicated picnic areas around its perimeter']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd

###
df11 = pd.DataFrame(df_dict)
df11.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJeRhEtqvHwoARn4vexuEKGnQ,"Vista Hermosa Natural Park, Mountains Recreati...","Trails lead to picnic areas, grassy fields, a ...","[park, tourist_attraction, parking, point_of_i...",4.7,2129,(213) 250-1100,https://mrca.ca.gov/parks/park-listing/vista-h...,0,"100 N Toluca St, Los Angeles, CA 90026, USA",Monday: 7:00 AM – 8:00 PM Tuesday: 7:00 AM – 8...,34.061873,-118.256886,Calm Romantic Sad Social,"Arts/Culture, Nature, Views, Free, Picnic Spots","Walk, Sightseeing, Picnics, Reflect",Take the time to walk around the dusty garden ...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJ_yD1_SK5woARmWLyCit3znQ&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Calm', 'Curious/Artsy', 'Sad', 'Social']
MoodList = ' '.join(Moods)
Categories = ['Arts/Culture', 'Nature','Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Learn' , 'Sightseeing', 'Reflect' ]
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['All of the actual tar pits and outdoor observation areas are free. However, If you want to visit the museum you will need to purchase tickets.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd


df12 = pd.DataFrame(df_dict)
df12.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJ_yD1_SK5woARmWLyCit3znQ,La Brea Tar Pits and Museum,Ice Age–fossil excavation site with an adjacen...,"[museum, tourist_attraction, point_of_interest...",4.6,11392,(213) 763-3499,http://tarpits.org/,0,"5801 Wilshire Blvd, Los Angeles, CA 90036, USA",Monday: 9:30 AM – 5:00 PM Tuesday: 9:30 AM – 5...,34.063738,-118.355451,Calm Curious/Artsy Sad Social,"Arts/Culture, Nature, Free","Learn, Sightseeing, Reflect",All of the actual tar pits and outdoor observa...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJsXW0WZg33YARSqFWwRGLWH0&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Energetic', 'Curious/Artsy']
MoodList = ' '.join(Moods)
Categories = ['Arts/Culture', 'Nature', 'Beaches', 'Views', 'Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Paint' , 'See Graffiti Art', 'Sightseeing', 'Adventure' ]
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['This location is ideal for those who like to live a little on the edge.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd


###
df13 = pd.DataFrame(df_dict)
df13.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJsXW0WZg33YARSqFWwRGLWH0,The Sunken City & Street Art,Abandoned beachfront area destroyed by a large...,"[tourist_attraction, point_of_interest, establ...",4.7,304,None,None,0,"San Pedro, CA 90731, USA",Monday: Open 24 hours Tuesday: Open 24 hours W...,33.706059,-118.290623,Energetic Curious/Artsy,"Arts/Culture, Nature, Beaches, Views, Free","Paint, See Graffiti Art, Sightseeing, Adventure",This location is ideal for those who like to l...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJX9JVNI65woARAltGGdhSBAA&fields=formatted_address%2Cuser_ratings_total%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Energetic', 'Social', 'Curious/Artsy', 'Sad']
MoodList = ' '.join(Moods)
Categories = [ 'Hikes', 'Nature',  'Views', 'Free', 'Gardens', 'Wildlife']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Hike' , 'Walk', 'Sightseeing','Gardens' 'Reflect']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['There are restrooms at the top in the visitor center.', 'Unfortunatly, dogs are not allowed.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd

###
df14 = pd.DataFrame(df_dict)
df14.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJX9JVNI65woARAltGGdhSBAA,Baldwin Hills Scenic Overlook,Hilltop park with views of Downtown Los Angele...,"[park, tourist_attraction, point_of_interest, ...",4.8,4283,(310) 558-5547,http://www.parks.ca.gov/?page_id=22790,0,"6300 Hetzler Rd, Culver City, CA 90232, USA",Monday: 6:00 AM – 9:00 PM Tuesday: 6:00 AM – 9...,34.0182,-118.381912,Energetic Social Curious/Artsy Sad,"Hikes, Nature, Views, Free, Gardens, Wildlife","Hike, Walk, Sightseeing, GardensReflect",There are restrooms at the top in the visitor ...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJBYuC8kvGwoAROxBTjwqfWpU&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =['Calm',  'Curious/Artsy']
MoodList = ' '.join(Moods)
Categories = [ 'Arts/Culture', 'Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Learn' , 'Walk', 'Sightseeing','Photography']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['You’re welcome to snap photos around the atrium as long as it’s not for a commercial purpose.','Unfortunately, even though The Bradbury is free to visit, outside visitors can only go up to the first landing of the stairs. Only tenants are allowed to go upstairs, and there is a security guard so don’t try to sneak up.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df15 = pd.DataFrame(df_dict)
df15.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJBYuC8kvGwoAROxBTjwqfWpU,Bradbury Building,Unique structure featuring a Victorian center ...,"[tourist_attraction, point_of_interest, establ...",4.5,1751,(213) 626-1893,https://www.laconservancy.org/locations/bradbu...,0,"304 S Broadway, Los Angeles, CA 90013, USA",Monday: 9:00 AM – 5:00 PM Tuesday: 9:00 AM – 5...,34.050604,-118.247857,Calm Curious/Artsy,"Arts/Culture, Free","Learn, Walk, Sightseeing, Photography",You’re welcome to snap photos around the atriu...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJ_YC-7LeWwoAR1WlzGnUnKMs&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = 'Situated in the Sun Valley, about 15 miles north from Downtown Los Angeles, Wat Thai replicates the traditional Buddhist temples in Thailand.  Beyond its physical structure, Wat Thai of Los Angeles not only serves as a religious purpose but as the cultural cent for the southern California Thai community.'
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Curious/Artsy', 'Social', 'Calm', 'Sad', 'Hungry/Thirsty']
MoodList = ' '.join(Moods)
Categories = [ 'Temples & Chapels', 'Thai','Arts/Culture', 'Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Learn' , 'Walk', 'Sightseeing','Eat']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['Every weekend, Thai Food vendors fill up this Temple\'s parking lot. The Thai food served here is famous. Make sure to arrive early because it gets busy.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df16 = pd.DataFrame(df_dict)
df16.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJ_YC-7LeWwoAR1WlzGnUnKMs,Wat Thai of Los Angeles,"Situated in the Sun Valley, about 15 miles nor...","[tourist_attraction, place_of_worship, point_o...",4.7,135,(818) 780-4200,https://www.watthailosangeles.com/,0,"8225 Coldwater Canyon Ave, North Hollywood, CA...",Monday: 8:00 AM – 7:00 PM Tuesday: 8:00 AM – 7...,34.22066,-118.414882,Curious/Artsy Social Calm Sad Hungry/Thirsty,"Temples & Chapels, Thai, Arts/Culture, Free","Learn, Walk, Sightseeing, Eat","Every weekend, Thai Food vendors fill up this ..."

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJRWV7oFlJ3YAR54yeHlo9KVc&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Curious/Artsy', 'Social', 'Calm', 'Sad', 'Romantic']
MoodList = ' '.join(Moods)
Categories = [ 'Temples & Chapels', 'Nature','Arts/Culture', 'Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Learn' , 'Walk', 'Sightseeing','Reflect']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['Explore the formal Rose Garden beside the chapel', 'See incredible views from Wayfarers Chapel.', 'Explore hillside trails near Rugged Portuguese Point, visible from the Wayfarers Chapel.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df17 = pd.DataFrame(df_dict)
df17.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJRWV7oFlJ3YAR54yeHlo9KVc,Wayfarers Chapel,"Airy stone-&-glass chapel, designed by Lloyd W...","[church, place_of_worship, point_of_interest, ...",4.7,563,(310) 377-1650,https://www.wayfarerschapel.org/?utm_source=gm...,0,"5755 Palos Verdes Dr S, Rancho Palos Verdes, C...",Monday: 9:00 AM – 5:00 PM Tuesday: 9:00 AM – 5...,33.744011,-118.377848,Curious/Artsy Social Calm Sad Romantic,"Temples & Chapels, Nature, Arts/Culture, Free","Learn, Walk, Sightseeing, Reflect",Explore the formal Rose Garden beside the chap...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJXaYsEk3GwoARvx7RKBUE8Zg&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Curious/Artsy', 'Social', 'Calm', 'Sad', 'Romantic']
MoodList = ' '.join(Moods)
Categories = [ 'Arts/Culture', 'Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Learn' , 'Explore Art','Reflect']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['Reserve tickets ahead of time', 'When you get to the museum, immediately reserve a time for both Infinity Mirrored Rooms', 'Download the Broad App for a guided tour on your phone.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df18 = pd.DataFrame(df_dict)
df18.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJXaYsEk3GwoARvx7RKBUE8Zg,The Broad,Modern art museum with a honeycomb-like facade...,"[art_gallery, tourist_attraction, museum, poin...",4.7,12151,(213) 232-6250,http://www.thebroad.org/,0,"221 S Grand Ave, Los Angeles, CA 90012, USA",Monday: Closed Tuesday: 11:00 AM – 5:00 PM Wed...,34.054502,-118.25018,Curious/Artsy Social Calm Sad Romantic,"Arts/Culture, Free","Learn, Explore Art, Reflect",Reserve tickets ahead of time||When you get to...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJkfZ_3AnIwoARTuGBq8QXyCI&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Curious/Artsy', 'Social', 'Calm','Sad' , 'Romantic']
MoodList = ' '.join(Moods)
Categories = [  'Arts/Culture','Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Learn' , 'Explore','Reflect']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['Admission is always free.', 'Reservations are not required.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df19 = pd.DataFrame(df_dict)
df19.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJkfZ_3AnIwoARTuGBq8QXyCI,California African American Museum,"Center presents art, culture & history exhibit...","[museum, tourist_attraction, point_of_interest...",4.6,1214,(213) 744-7432,http://www.caamuseum.org/,0,"600 State Dr, Los Angeles, CA 90037, USA",Monday: Closed Tuesday: Closed Wednesday: 10:0...,34.015885,-118.283484,Curious/Artsy Social Calm Sad Romantic,"Arts/Culture, Free","Learn, Explore, Reflect",Admission is always free.||Reservations are no...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJbzYnQte8woARJaqqFVpKeNo&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Curious/Artsy', 'Social', 'Calm',  'Romantic', 'Sad', 'Studious']
MoodList = ' '.join(Moods)
Categories = [  'Arts/Culture','Gardens', 'Free']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Learn' , 'Explore Art','Reflect']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['Admission is free.', 'Reservations are required.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df20 = pd.DataFrame(df_dict)
df20.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJbzYnQte8woARJaqqFVpKeNo,The Getty,"Famous, sizable free museum highlighting Ameri...","[tourist_attraction, museum, point_of_interest...",4.8,25689,(310) 440-7300,https://www.getty.edu/visit/center/,0,"1200 Getty Center Dr, Los Angeles, CA 90049, USA",Monday: Closed Tuesday: 10:00 AM – 5:30 PM Wed...,34.078036,-118.474095,Curious/Artsy Social Calm Romantic Sad Studious,"Arts/Culture, Gardens, Free","Learn, Explore Art, Reflect",Admission is free.||Reservations are required.

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJY4yAluLHwoAR7y--92aDHbQ&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[  'Social', 'Calm',  'Romantic', 'Curious/Artsy', 'Studious']
MoodList = ' '.join(Moods)
Categories = [  'Arts/Culture', 'Gardens','Nature' ,'Free', 'Picnic Spots']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Walk' , 'Sightseeing','Relax', 'Gardens', 'Benches']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['This is a free garden.', 'The Exposition Park Rose Garden is a historic 7-acre sunken garden located in Exposition Park in Los Angeles, California. It has been called "one of the city\'s best-kept secrets".']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df21 = pd.DataFrame(df_dict)
df21.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJY4yAluLHwoAR7y--92aDHbQ,Exposition Park Rose Garden,Cheerful formal park featuring a collection of...,"[tourist_attraction, park, point_of_interest, ...",4.7,2102,(213) 763-0114,http://www.laparks.org/exporosegarden/rosegard...,0,"701 State Dr, Los Angeles, CA 90037, USA",Monday: 9:00 AM – 7:30 PM Tuesday: 9:00 AM – 7...,34.017351,-118.285924,Social Calm Romantic Curious/Artsy Studious,"Arts/Culture, Gardens, Nature, Free, Picnic Spots","Walk, Sightseeing, Relax, Gardens, Benches",This is a free garden.||The Exposition Park Ro...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJB_8Iy1C_woARO-B5t-OFmpM&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=2
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Sad', 'Hungry/Thirsty',  'Romantic']
MoodList = ' '.join(Moods)
Categories = [  'Thai', 'Restaurants']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Eat' , 'Drink','Socialize']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['This Thai Restaurant has a wide variety of tasty dishes. This includes: ', 'Pad See Ew', 'Papaya Salad', 'Morning Glory', 'Pad Thai']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df22 = pd.DataFrame(df_dict)
df22.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJB_8Iy1C_woARO-B5t-OFmpM,Ruen Pair,Modest eatery bustles with foodies who come fo...,"[restaurant, point_of_interest, food, establis...",4.5,665,(323) 466-0153,http://ruenpairthai.com/,2,"5257 Hollywood Blvd, Los Angeles, CA 90027, USA",Monday: 4:00 – 11:00 PM Tuesday: 4:00 – 11:00 ...,34.102047,-118.305467,Sad Hungry/Thirsty Romantic,"Thai, Restaurants","Eat, Drink, Socialize",This Thai Restaurant has a wide variety of tas...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJF5-xKVnGwoARobBf9Z2okrM&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=2
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Sad', 'Hungry/Thirsty',  'Romantic']
MoodList = ' '.join(Moods)
Categories = [ 'Restaurants', 'Vietnamese']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Eat' , 'Drink','Socialize']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['Make sure yout try their Pho, its what this place is known for', 'Order a Thai Tea for a tasty way to relieve a spicy mouth.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df23 = pd.DataFrame(df_dict)
df23.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJF5-xKVnGwoARobBf9Z2okrM,Phở 87,"Pho, spring rolls & other casual Vietnamese fa...","[restaurant, point_of_interest, food, establis...",4.5,1269,(323) 227-0758,None,2,"1019 N Broadway, Los Angeles, CA 90012, USA",Monday: 11:00 AM – 8:00 PM Tuesday: Closed Wed...,34.06735,-118.235705,Sad Hungry/Thirsty Romantic,"Restaurants, Vietnamese","Eat, Drink, Socialize","Make sure yout try their Pho, its what this pl..."

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJEWvw-dLBwoARkYj5myw6LmY&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=1
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = 'Villa\'s tacos started off just a couple of years ago by serving Mexican food from their home. Since then they have wom multiple awards for best tacos in LA. Their tacos are unique and delicious.'
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Sad', 'Hungry/Thirsty',  'Romantic']
MoodList = ' '.join(Moods)
Categories = [ 'Mexican', 'Restaurants']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Eat' , 'Drink','Socialize']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['This pop up taco stand has won multiple awards for its blue corn tortilla tacos. Make sure to try some.', 'They also serve aguas frescas here.', 'This taco stand is on York which features a lpot of other restaurants, food stands, and food trucks.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df24 = pd.DataFrame(df_dict)
df24.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJEWvw-dLBwoARkYj5myw6LmY,Villas Tacos Los Angeles,Villa's tacos started off just a couple of yea...,"[restaurant, food, point_of_interest, establis...",4.8,108,None,https://www.instagram.com/villastacoslosangeles/,1,"5052 York Blvd, Los Angeles, CA 90042, USA",Monday: Closed Tuesday: 4:00 – 10:00 PM Wednes...,34.121036,-118.205218,Sad Hungry/Thirsty Romantic,"Mexican, Restaurants","Eat, Drink, Socialize",This pop up taco stand has won multiple awards...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJteZy8jzJwoARldQote7Uc1k&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=1
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Sad', 'Hungry/Thirsty',  'Romantic', 'Focused']
MoodList = ' '.join(Moods)
Categories = [ 'Coffee & Tea', 'Mexican','Restaurants' ]
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Eat' , 'Drink','Socialize']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['Some popular menu items are the Mocha Mexicano, Horchata Frappe, and the Coco Loco Latte.', 'There are many locations throughout LA, just look up Tierra Mia Coffee.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df25 = pd.DataFrame(df_dict)
df25.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJteZy8jzJwoARldQote7Uc1k,Tierra Mia Coffee,Stylish chain serving Latin-inspired coffee dr...,"[cafe, store, food, point_of_interest, establi...",4.6,1944,None,http://www.tierramiacoffee.com/,1,"6706 Pacific Blvd, Huntington Park, CA 90255, USA",Monday: 6:00 AM – 11:00 PM Tuesday: 6:00 AM – ...,33.978484,-118.224817,Sad Hungry/Thirsty Romantic Focused,"Coffee & Tea, Mexican, Restaurants","Eat, Drink, Socialize",Some popular menu items are the Mocha Mexicano...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJ7UPWdzXGwoARv3xPWAYT0ok&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Sad', 'Energetic',  'Social', 'Calm', 'Hungry/Thirsty']
MoodList = ' '.join(Moods)
Categories = [ 'Bar', 'Mexican', 'Restaurant']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Dance', 'Drink','Eat']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['If you\'re hungry you\'re in luck because this place serves street style Mexican food that is cooked in front of you.', 'Free entrance but if you want to drink you must pay']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df26 = pd.DataFrame(df_dict)
df26.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJ7UPWdzXGwoARv3xPWAYT0ok,Las Perlas,Hipsters pack this stylish Mexican hot spot fo...,"[bar, point_of_interest, establishment]",4.4,532,(213) 988-8355,http://lasperlasla.com/,0,"107 E 6th St, Los Angeles, CA 90014, USA",Monday: 5:00 PM – 2:00 AM Tuesday: 5:00 PM – 2...,34.045098,-118.249513,Sad Energetic Social Calm Hungry/Thirsty,"Bar, Mexican, Restaurant","Dance, Drink, Eat",If you're hungry you're in luck because this p...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJR4OR2Gm5woARYeNiaa3p4zs&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Sad', 'Energetic',  'Social']
MoodList = ' '.join(Moods)
Categories = [ 'Bar', 'Club']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Dance', 'Drink','Eat']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['This bar features a quirky ATM entrance and a fun light up dance floor.','There a live dancing shows that happen on the stage throught the night.', 'Free entrance but if you want to drink you must pay']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df27 = pd.DataFrame(df_dict)
df27.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJR4OR2Gm5woARYeNiaa3p4zs,Kiss Kiss Bang Bang,None,"[night_club, bar, point_of_interest, establish...",3.9,55,(213) 381-7411,http://kisskissbangbangla.com/,0,"3531 Wilshire Blvd, Los Angeles, CA 90010, USA",Monday: Closed Tuesday: Closed Wednesday: 7:00...,34.062113,-118.301459,Sad Energetic Social,"Bar, Club","Dance, Drink, Eat",This bar features a quirky ATM entrance and a ...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJs0m6S-W5woARXqGSXVB4EYw&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = 'Malik Books is an independent Black Owned Bookstore that specializes in books, calendars, and gifts full of cultural diversity.  Our selection of books and gifts has help create a positive impact on self-reflection, self-esteem, and self-awareness.   Malik Books motto is "Change Your Thoughts Change Your Life".  Our goal at Malik books is to give our customers an African American experience  of pride and cultural.   Malik Books is your friendly neighborhood bookstore with all your good reads from children to adult books.   Support Local Bookstores and  Shop Online with Bookshop/malikbooks.'
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Calm', 'Curious/Artsy',  'Social', 'Studious']
MoodList = ' '.join(Moods)
Categories = [ 'Black Owned', 'Bookstores', 'Arts/Culture']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Learn', 'Read','Relax', 'Browse']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['This is a Black Owned Buiness.']
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df28 = pd.DataFrame(df_dict)
df28.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJs0m6S-W5woARXqGSXVB4EYw,Malik Books,Malik Books is an independent Black Owned Book...,"[book_store, store, point_of_interest, establi...",4.8,82,(323) 389-8040,https://malikbooks.com/,0,"3650 W Martin Luther King Jr Blvd Ste 245, Los...",Monday: 10:00 AM – 9:00 PM Tuesday: 10:00 AM –...,34.009868,-118.337178,Calm Curious/Artsy Social Studious,"Black Owned, Bookstores, Arts/Culture","Learn, Read, Relax, Browse",This is a Black Owned Buiness.

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJidp6qa3AwoAR1ALo3QLZyj8&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=1
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Hungry/Thirsty', 'Studious']
MoodList = ' '.join(Moods)
Categories = [ 'Women Owned', 'Restaurants', 'Mexican', 'American']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Eat', 'Drink','Relax', 'Socialize']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['Briana grew up in Texas and eventually found herself in California. She missed the food she knew and loved back home. That’s when she decided to bring some of that Texan hospitality and good eats to Los Angeles. She opened up Home State Hollywood, where people can enjoy breakfast tacos, burritos, and queso―all while having a sense of belonging and community.', 'Make sure to try their breakfast tacos!' ]
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df29 = pd.DataFrame(df_dict)
df29.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJidp6qa3AwoAR1ALo3QLZyj8,HomeState,"Warm, rustic cafe fixing up tacos, queso & Tex...","[meal_takeaway, restaurant, food, point_of_int...",4.6,1091,(323) 906-1122,https://www.myhomestate.com/hollywood-blvd-los...,1,"4624 Hollywood Blvd, Los Angeles, CA 90027, USA",Monday: 8:00 AM – 10:00 PM Tuesday: 8:00 AM – ...,34.099871,-118.290135,Hungry/Thirsty Studious,"Women Owned, Restaurants, Mexican, American","Eat, Drink, Relax, Socialize",Briana grew up in Texas and eventually found h...

In [ ]:
#Code to collect information from each lcoation


params = {}
### MODIFY THE URL BELOW
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJ_w8sTTRI3YAR_IJyQgtzDSs&fields=formatted_address%2Cname%2Cplace_id%2Crating%2Cgeometry%2Ccurrent_opening_hours%2Cformatted_phone_number%2Cwebsite%2Cprice_level%2Crating%2Ceditorial_summary%2Ctype%2Cuser_ratings_total&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)

Types = []
try:
  Types.append(results['result']['types'])
except:
  Types.append('None')
try:
  Location_ID = results['result']['place_id']
except:
  Location_ID ='None'
try:
  Name = results['result']['name']
except:
  Name = 'None'
try:
  Address = results['result']['formatted_address']
except:
  Address='None'
try:
  Lat=results['result']['geometry']['location']['lat']
except:
  Lat='None'
try:
  Lon=results['result']['geometry']['location']['lng']
except:
  Lon='None'
try:
  Rating=results['result']['rating']
except:
  Rating='None'
try:
  Website=results['result']['website']
except:
  Website='None'
try:
  Price_Level=0
except:
  Price_Level='None'
try:
  Phone = results['result']['formatted_phone_number']
except:
  Phone='None'
try:
  Summary = results['result']['editorial_summary']['overview']
except:
  Summary='None'
try:
  Opening_Hours = results['result']['current_opening_hours']['weekday_text']
  Opening_HoursList = ' '.join(Opening_Hours)
except:
  Opening_HoursList = 'None'
try:
  TotalReviews = results['result']['user_ratings_total']
except:
  TotalReviews='None'

Moods =[ 'Calm', 'Energetic', 'Romantic', 'Curious/Artsy', 'Sad', 'Social', 'Studious']
MoodList = ' '.join(Moods)
Categories = [ 'Nature', 'Beaches', 'Wildlife', 'Views', 'Picnic Spots']
CategoryList =  ', '.join(Categories)


ThingsToDo = ['Relax at the beach', 'Play with sea life','Enjoy beautiful views']
ThingsToDoList =  ', '.join(ThingsToDo)

InsiderTips = ['You can find all sorts of wildlife here like Starfish, Sear Urchins, Crabs, and much more', 'Please be respectful of the wildlife and no not take anything home or remove them from their enviorment.' ]
InsiderTipsList =  '||'.join(InsiderTips)





df_dict = {'Place ID': Location_ID, 'Name' : Name, 'Summary': Summary, 'Types': Types, "Rating": Rating , 'Total Reviews': TotalReviews,'Phone Number':Phone,  "Website": Website, "Price Level": Price_Level,  'Address': Address, 'Hours': Opening_HoursList,'Latitude': Lat,  'Longitude': Lon, 'Moods': MoodList, 'Categories': CategoryList,'Things To Do': ThingsToDoList, 'Insider Tips': InsiderTipsList  }
import pandas as pd
###
df30 = pd.DataFrame(df_dict)
df30.head()

,Place ID,Name,Summary,Types,Rating,Total Reviews,Phone Number,Website,Price Level,Address,Hours,Latitude,Longitude,Moods,Categories,Things To Do,Insider Tips
0,ChIJ_w8sTTRI3YAR_IJyQgtzDSs,White Point Park,"Park & beach with lots of sea creatures, plus ...","[park, tourist_attraction, point_of_interest, ...",4.7,3460,None,None,0,"1801 W Paseo Del Mar, San Pedro, CA 90732, USA",Monday: 6:30 AM – 8:30 PM Tuesday: 6:30 AM – 8...,33.718124,-118.321607,Calm Energetic Romantic Curious/Artsy Sad Soci...,"Nature, Beaches, Wildlife, Views, Picnic Spots","Relax at the beach, Play with sea life, Enjoy ...",You can find all sorts of wildlife here like S...

In [ ]:
frames = [df0, df1, df01, df2, df3,df4, df5, df6, df7,df8, df9, df10, df11,df12, df13, df14, df15,df16, df17, df18, df19,df20, df21, df22, df23, df24, df25,df26,df27,df28,df29, df30]
result = pd.concat(frames)
result
result.loc[result["Price Level"] =="None", "Price Level"] = 0
result
from google.colab import files
result.to_csv('Locations.csv') 
files.download('Locations.csv')