In [ ]:
import requests
import json
import time

In [ ]:
Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJqaVeK1pJ3YARz9AXOaoNev0&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df0 = pd.DataFrame(df_dict)

df0.head()

,Place ID,Photo ID
0,ChIJqaVeK1pJ3YARz9AXOaoNev0,AfLeUgO7K0NBh0vfLxjZ_3vnYzgjeBEZaJJ7KGULB86ptw...
1,ChIJqaVeK1pJ3YARz9AXOaoNev0,AfLeUgMQ9_rqrgwp0zbkYPK3L8Cg-dtUiCsZNTu7rYzIoJ...
2,ChIJqaVeK1pJ3YARz9AXOaoNev0,AfLeUgN4hT1mDLW_eAoJPsbf9qJRgPm4S892Pn4FQNntFS...
3,ChIJqaVeK1pJ3YARz9AXOaoNev0,AfLeUgOXBXTckS2JTwZkgs5S9kVyQ8KAVkZHNWeKivyDOl...
4,ChIJqaVeK1pJ3YARz9AXOaoNev0,AfLeUgPe5n-2PctJNmNWd0gaLT17U_Yr8F66vzguJEEKbU...

In [ ]:
Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJiXJav6K6woARGPmX6Bsp55Y&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df1 = pd.DataFrame(df_dict)

df1.head()

,Place ID,Photo ID
0,ChIJiXJav6K6woARGPmX6Bsp55Y,AfLeUgNwPxu_f-4zdIdPFoqRtaZyhIHj1Mz_Q_O8oNmZMu...
1,ChIJiXJav6K6woARGPmX6Bsp55Y,AfLeUgO4bTk5DsDpQySHauARc_2DvKbRx29_WKUe-Axady...
2,ChIJiXJav6K6woARGPmX6Bsp55Y,AfLeUgPA9FBC9E6zfl11vsH_66Au4gaeBvwaTi9Vvkjqz1...
3,ChIJiXJav6K6woARGPmX6Bsp55Y,AfLeUgNXgZBo0_TksQcPneKy1PoMLcLf0DmUVPWuTa_CNx...
4,ChIJiXJav6K6woARGPmX6Bsp55Y,AfLeUgOEVvfz05MzkhI-pMXLz9rWW6dxuZAWe8UXKQ7qcc...

In [ ]:
Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJ7YJ_IkrGwoARNak4CDihkYU&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df2 = pd.DataFrame(df_dict)

df2.head()

,Place ID,Photo ID
0,ChIJ7YJ_IkrGwoARNak4CDihkYU,AfLeUgMvhJU2es_R5w-rqUd4Ygz4i2oS7fj32EVTtNFsEf...
1,ChIJ7YJ_IkrGwoARNak4CDihkYU,AfLeUgMogXxRPEr52AJr5qAPlQk8SYggyS7Uh5QU-YYqO1...
2,ChIJ7YJ_IkrGwoARNak4CDihkYU,AfLeUgO5TaMSlCU8b_XRYB-hBfoec2Agb00ODrggN0YmZh...
3,ChIJ7YJ_IkrGwoARNak4CDihkYU,AfLeUgPnrH83SAx89eesVzRZGy_rgFymp4ebX-stuzpxj2...
4,ChIJ7YJ_IkrGwoARNak4CDihkYU,AfLeUgNoL9GsJ5N2b-2a7SpEMwYnQOuIywRZPat9gWWV0B...

In [ ]:
Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJhSKS_KBU6YARVsELBhsoDi0&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df3 = pd.DataFrame(df_dict)

df3.head()

,Place ID,Photo ID
0,ChIJhSKS_KBU6YARVsELBhsoDi0,AfLeUgNK_EMqh3vgQPN_MtxODgLwfyHMZbcRSsj8SgZhvN...
1,ChIJhSKS_KBU6YARVsELBhsoDi0,AfLeUgPdFPTQUcVoqCzLN9Iyi9Ya5eqXl9pBsMhVXxv_gp...
2,ChIJhSKS_KBU6YARVsELBhsoDi0,AfLeUgMg-XFC9oy5Nj3q0dTTBHcOeM2QgtW2gS8uNf4m2s...
3,ChIJhSKS_KBU6YARVsELBhsoDi0,AfLeUgMKeh4UqJq0Lg22TpZQPiI-FU0XH020U8KgsJ9vjm...
4,ChIJhSKS_KBU6YARVsELBhsoDi0,AfLeUgPgiuAXQ5CA4SyJW0cNQU356sL4QjbGxEXI4Q5HnY...

In [ ]:
Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJE8IF_yHN3IARaEQ5vCdOgwA&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df4 = pd.DataFrame(df_dict)

df4.head()

,Place ID,Photo ID
0,ChIJE8IF_yHN3IARaEQ5vCdOgwA,AfLeUgODA9iTDPhRADG9tpxXmMFTjMqs1hdDzgfiCtY2wS...
1,ChIJE8IF_yHN3IARaEQ5vCdOgwA,AfLeUgOvbJBlcjz9PUJ8mIf1nsBbeUb-khXzDo_53NHlDv...
2,ChIJE8IF_yHN3IARaEQ5vCdOgwA,AfLeUgPz7NZrZL9YXL0qoOejJSHwZNret6p6kX5Ch6z_HF...
3,ChIJE8IF_yHN3IARaEQ5vCdOgwA,AfLeUgM-C1-ZcseyU0Tdzv4dXGKyiMTNQXmPEMcHC7V82-...
4,ChIJE8IF_yHN3IARaEQ5vCdOgwA,AfLeUgOhPIgvYQf0-JX_BfmJOAdmQzQdCxhWvxYZnudC0d...

In [ ]:
Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJLYsuqGq8woARw5HvSGCXO8E&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df5 = pd.DataFrame(df_dict)
df5.head()

,Place ID,Photo ID
0,ChIJLYsuqGq8woARw5HvSGCXO8E,AfLeUgMBb0BpBNbuw00iEGrrOKNVsz5Yypdh7y7nBzkqtS...
1,ChIJLYsuqGq8woARw5HvSGCXO8E,AfLeUgM31IRrYWUvbg6EC4URpFpjTQEq8mbTFQLSZM9GZD...
2,ChIJLYsuqGq8woARw5HvSGCXO8E,AfLeUgOqwpRzr_1homdr1D2UsDAQH9LT-g17zA18mYIO0p...
3,ChIJLYsuqGq8woARw5HvSGCXO8E,AfLeUgMNNxcZnHud1Fvk-kx3j_0JwvFCFLqlOP_ZTfPRCo...
4,ChIJLYsuqGq8woARw5HvSGCXO8E,AfLeUgNbjewFN09OG5_HUgyBRZA32-VC_1_HkgfuZqUwvd...

In [ ]:
Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJGQN5oX2_woARuEam6IqPTmo&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df6 = pd.DataFrame(df_dict)
df6.head()

,Place ID,Photo ID
0,ChIJGQN5oX2_woARuEam6IqPTmo,AfLeUgM8GvmfyliNhoHVJ46v4cEywosK5-R3ig1sjMl4j4...
1,ChIJGQN5oX2_woARuEam6IqPTmo,AfLeUgNAFAFNDjEeMH1I5ar-8YqCVyA5dyerldt1qdTrdp...
2,ChIJGQN5oX2_woARuEam6IqPTmo,AfLeUgMoqB-V19h4L4w4S9yIKGcW8SerAAR5Ng-6UAyiFo...
3,ChIJGQN5oX2_woARuEam6IqPTmo,AfLeUgMTHJvEojtA1j3wTAX1drYIMLWVFphEGT1dRczeG6...
4,ChIJGQN5oX2_woARuEam6IqPTmo,AfLeUgNn6MWrxX-ykvf0Gd6OQpuZESEt9AxybIr3QDXI0j...

In [ ]:
Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJa_vDely_woAR7bHQTLLrWrI&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df7 = pd.DataFrame(df_dict)
df7.head()

,Place ID,Photo ID
0,ChIJa_vDely_woAR7bHQTLLrWrI,AfLeUgPnZCxvWuVSI98ENDP-rewrTUKiFKKj_P7Pmm_2uR...
1,ChIJa_vDely_woAR7bHQTLLrWrI,AfLeUgP4fxy4cZzwuNRfksLx89O53Qhsan-WZrduxUOT6X...
2,ChIJa_vDely_woAR7bHQTLLrWrI,AfLeUgM3G1B_DesR8tiJLlvJnKkhBuroLXivatYtyzFtnT...
3,ChIJa_vDely_woAR7bHQTLLrWrI,AfLeUgNIg0f042eK9-x-RBbGxyCbLp9J73lT8G80ztgKTz...
4,ChIJa_vDely_woAR7bHQTLLrWrI,AfLeUgPvoCGKsAtsd4V4hmw663wXcDz25Qr7R7Ys79trUv...

In [ ]:
Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJvXdlhBvHwoARfS5LNYPCnEQ&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df8 = pd.DataFrame(df_dict)
df8.head()

,Place ID,Photo ID
0,ChIJvXdlhBvHwoARfS5LNYPCnEQ,AfLeUgOo9IcV1_N4n2jcVgWFGnwNYikStVVMZgdfQfKQtV...
1,ChIJvXdlhBvHwoARfS5LNYPCnEQ,AfLeUgMMNoXC2fB6boHInvkrUD04dTvDvsNe4oKMiAP36_...
2,ChIJvXdlhBvHwoARfS5LNYPCnEQ,AfLeUgOi9RMaXJHDy4DW2NRd2_pa2CFG0PYTm0CmBhpOdY...
3,ChIJvXdlhBvHwoARfS5LNYPCnEQ,AfLeUgOI-b4u1aaDAiWJSN8cdY0Maq_HxQ5Ku5swSnehBl...
4,ChIJvXdlhBvHwoARfS5LNYPCnEQ,AfLeUgMUIfQZiq66h00BkMwZjTwJYdWEfJjNab2uMeirrV...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJT9Of3GeWwoARDyyechrb21w&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd


df9 = pd.DataFrame(df_dict)
df9.head()

,Place ID,Photo ID
0,ChIJT9Of3GeWwoARDyyechrb21w,AfLeUgOgrMhWXk89aHpfNjBWY8y1MRkCpep5kSVcX6KsgT...
1,ChIJT9Of3GeWwoARDyyechrb21w,AfLeUgMR2SVQgvZvkai1GgFznyanre20TzgQQetMsz1AKt...
2,ChIJT9Of3GeWwoARDyyechrb21w,AfLeUgMROCIBsKltb_a5rXg12S_O4fCTX8FkLeQivYdwbf...
3,ChIJT9Of3GeWwoARDyyechrb21w,AfLeUgPmIPDsLWzUhysyJoZzuXJnixxvF7spd49jHrIF6u...
4,ChIJT9Of3GeWwoARDyyechrb21w,AfLeUgOq1j03KCWMCUB2Mcj-MG83vrkVMq5dS_sqYeTVdi...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJ7wJnBuzGwoARD2vr4e0AnWU&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df10 = pd.DataFrame(df_dict)
df10.head()

,Place ID,Photo ID
0,ChIJ7wJnBuzGwoARD2vr4e0AnWU,AfLeUgPY5o9hjUnLmzr_LvHW0CuQcUiBI3pFbx4E_SWMEG...
1,ChIJ7wJnBuzGwoARD2vr4e0AnWU,AfLeUgOweXnfFo1gq1i2p9kSht8mz_aPJFI1wpqpfUig74...
2,ChIJ7wJnBuzGwoARD2vr4e0AnWU,AfLeUgMc4i-jQypeJ5qwZ68dhCofhIpN7MW7tEFeiTeNZB...
3,ChIJ7wJnBuzGwoARD2vr4e0AnWU,AfLeUgNz1G2R_GfI0X3M0AI5X7n9jn8AK4c385BsDDJqPK...
4,ChIJ7wJnBuzGwoARD2vr4e0AnWU,AfLeUgMINHImbOVCvgzYy2J7Qi5PZAnwYXzu_4EoGI3N9-...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJeRhEtqvHwoARn4vexuEKGnQ&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df11 = pd.DataFrame(df_dict)
df11.head()

,Place ID,Photo ID
0,ChIJeRhEtqvHwoARn4vexuEKGnQ,AfLeUgMec9xngYIGS1x7jhmyKG8QTbTsbOoSkWuT4pWvJ-...
1,ChIJeRhEtqvHwoARn4vexuEKGnQ,AfLeUgPa4oGMOk8ARvpTyol5I5eFX5RUIggJmcDhSpPhF8...
2,ChIJeRhEtqvHwoARn4vexuEKGnQ,AfLeUgNClFpcu1hh9uLWAQovwzqW6alskSNKmdpMMUoosF...
3,ChIJeRhEtqvHwoARn4vexuEKGnQ,AfLeUgPnrzMyvkDI4lUWIe540BPQgFGtsmsCpqvxPCwjpW...
4,ChIJeRhEtqvHwoARn4vexuEKGnQ,AfLeUgNGShsBcZYz2lRkEyGIk03vkPZajpULhlH9LYs2EZ...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJ_yD1_SK5woARmWLyCit3znQ&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df12 = pd.DataFrame(df_dict)
df12.head()

,Place ID,Photo ID
0,ChIJ_yD1_SK5woARmWLyCit3znQ,AfLeUgPvq-gQiwBRosiX5IGW_uiFY5eMrR5crUhxGBuR-z...
1,ChIJ_yD1_SK5woARmWLyCit3znQ,AfLeUgNjE0pPDeYtjEsl08xA4BNQsRoBSQvzxEbjCmZthN...
2,ChIJ_yD1_SK5woARmWLyCit3znQ,AfLeUgPvigR9rSPiGojTFZnhzxWBB7V6PaMSLy9Xkd4Xrm...
3,ChIJ_yD1_SK5woARmWLyCit3znQ,AfLeUgP5SM1KtWZOuCy9FNbYSzh3UyU4YtXxbnRyTPJytL...
4,ChIJ_yD1_SK5woARmWLyCit3znQ,AfLeUgPzBIyxir59ppyldDjTDfUZ739Av9os5zaaauacZs...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJsXW0WZg33YARSqFWwRGLWH0&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df13 = pd.DataFrame(df_dict)
df13.head()

,Place ID,Photo ID
0,ChIJsXW0WZg33YARSqFWwRGLWH0,AfLeUgOJlov6H7fM--msXdFPbQ5qhFu8-onmfwFSqIpdUe...
1,ChIJsXW0WZg33YARSqFWwRGLWH0,AfLeUgPhaPBKKUkhfsJvSFXV1A_TptwMcsSrA403Jb5lzK...
2,ChIJsXW0WZg33YARSqFWwRGLWH0,AfLeUgNX2p3MZLJ0lNrzAfv3XkQWuyNqClhOj6rrmEFAiC...
3,ChIJsXW0WZg33YARSqFWwRGLWH0,AfLeUgMmYdtvYP7eHeq0UBTdM9SBw6XE8G84OzFjgPNyCL...
4,ChIJsXW0WZg33YARSqFWwRGLWH0,AfLeUgM4A1tKLA6-6JQJIYjDrUglNrOXddvxVvbhSgdZPb...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJX9JVNI65woARAltGGdhSBAA&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df14 = pd.DataFrame(df_dict)
df14.head()

,Place ID,Photo ID
0,ChIJX9JVNI65woARAltGGdhSBAA,AfLeUgMvcmzQLqQT5BCc6n5EREqLmCZd8Vz7mnlmSheGuO...
1,ChIJX9JVNI65woARAltGGdhSBAA,AfLeUgNYnesr_nUCNcnxN16rP1o4IZZ19O6BRmQFFS4Kaa...
2,ChIJX9JVNI65woARAltGGdhSBAA,AfLeUgPD2X1NhWcOqFC-pePj2bpnWiObubVjhoHOo6D9FM...
3,ChIJX9JVNI65woARAltGGdhSBAA,AfLeUgMmzpI0Kpn4NDdQiqiuDab9HQp95SvBNp9Mylq3Iu...
4,ChIJX9JVNI65woARAltGGdhSBAA,AfLeUgORqeHxPixDmRGaINhH1mQ7spbhhh8DkGEbx6i6kc...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJBYuC8kvGwoAROxBTjwqfWpU&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df15 = pd.DataFrame(df_dict)
df15.head()

,Place ID,Photo ID
0,ChIJBYuC8kvGwoAROxBTjwqfWpU,AfLeUgOSHqw11_7gYkGnoGNiZjUaBl5ZDFB0IvpRZf7eWA...
1,ChIJBYuC8kvGwoAROxBTjwqfWpU,AfLeUgMsuw5nc3quueyHIH6jaRPXVqYUd0piGaZg8TBzh8...
2,ChIJBYuC8kvGwoAROxBTjwqfWpU,AfLeUgN4avhvvjC8xy8tcqRKthLMuJ2r43W_l7SJujGJHs...
3,ChIJBYuC8kvGwoAROxBTjwqfWpU,AfLeUgMOMQ1ZdPH1868KHQjPNS-_g7nq_tO7gDnAbLEtsR...
4,ChIJBYuC8kvGwoAROxBTjwqfWpU,AfLeUgORW0Om3tskeHABURtPTYM2U72VyrE8TpqTXutaoB...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJ_YC-7LeWwoAR1WlzGnUnKMs&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df16 = pd.DataFrame(df_dict)
df16.head()

,Place ID,Photo ID
0,ChIJ_YC-7LeWwoAR1WlzGnUnKMs,AfLeUgODlEh_KR9zwI2ZPdjvTZv9vQKu3nZ9WM81s9dcp-...
1,ChIJ_YC-7LeWwoAR1WlzGnUnKMs,AfLeUgMNNq9kdQvxaAV213HAIHyg718tdslEbcIkt7gh5h...
2,ChIJ_YC-7LeWwoAR1WlzGnUnKMs,AfLeUgP9NE1XlvznzZQklcmReGN3nYTevRu_X7L6VUBmQB...
3,ChIJ_YC-7LeWwoAR1WlzGnUnKMs,AfLeUgPeFD-gT7XGzxo0MfxAtbKXUQFsJHgVmo3NvrvksD...
4,ChIJ_YC-7LeWwoAR1WlzGnUnKMs,AfLeUgMHkytPwwa6oAa1NEdwxGrGtwZCM2-wCqBnyvLWWl...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJRWV7oFlJ3YAR54yeHlo9KVc&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df17 = pd.DataFrame(df_dict)
df17.head()

,Place ID,Photo ID
0,ChIJRWV7oFlJ3YAR54yeHlo9KVc,AfLeUgMPtjxtRd-pVBhv8xFSEvavlTW3mY-UILgsdoblpY...
1,ChIJRWV7oFlJ3YAR54yeHlo9KVc,AfLeUgPi9ZjMREdko2guLWmChfrpKaGifLQ4hE9dTZVODT...
2,ChIJRWV7oFlJ3YAR54yeHlo9KVc,AfLeUgOKsfA3jTpIRtNW0B34vHJVyT2IUUp6mVY9wHG6v5...
3,ChIJRWV7oFlJ3YAR54yeHlo9KVc,AfLeUgPb9YcgJOA3g_1cdCvOH3uR6tYkQwbw6a-BFRR8L6...
4,ChIJRWV7oFlJ3YAR54yeHlo9KVc,AfLeUgN8olnzvsmpuyhAl5UZQa6Fcwx9X51j-Se53FT6cb...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJXaYsEk3GwoARvx7RKBUE8Zg&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df18 = pd.DataFrame(df_dict)
df18.head()

,Place ID,Photo ID
0,ChIJXaYsEk3GwoARvx7RKBUE8Zg,AfLeUgNLgqD_tH5PONdPEIY4cI4NR3S3DN6bEga45TEkrC...
1,ChIJXaYsEk3GwoARvx7RKBUE8Zg,AfLeUgOGyZQMIU-TqM-r9lP1Pw0l8RmCVSoKzErqjXF9vL...
2,ChIJXaYsEk3GwoARvx7RKBUE8Zg,AfLeUgPeTWTgyNjKwUyl2JDtWMdnNS-OlFSBFm-MUomt1n...
3,ChIJXaYsEk3GwoARvx7RKBUE8Zg,AfLeUgPnLkYVFrUmD3LdKUingoYKrBX6nthVw0xU5UgWhS...
4,ChIJXaYsEk3GwoARvx7RKBUE8Zg,AfLeUgMX3C-1bWWFssWPu2rU1Pb_tajGRsM_iUgNNFXpOu...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJkfZ_3AnIwoARTuGBq8QXyCI&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df19 = pd.DataFrame(df_dict)
df19.head()

,Place ID,Photo ID
0,ChIJkfZ_3AnIwoARTuGBq8QXyCI,AfLeUgOqaBN3an47UOaq8oh4tHPGBcsREOj_WQ55Nunmdg...
1,ChIJkfZ_3AnIwoARTuGBq8QXyCI,AfLeUgMhOLu6EhyDF5VVSPzFxE513zJfZaN7YkbMP4UaWX...
2,ChIJkfZ_3AnIwoARTuGBq8QXyCI,AfLeUgMFjvyQz_saNSucyZ26qVVT-2lFz5V7yHaTN83q3K...
3,ChIJkfZ_3AnIwoARTuGBq8QXyCI,AfLeUgOQJD2vsIiFL0S47Z1Bfhr8uMjO31RwWzAuD433KB...
4,ChIJkfZ_3AnIwoARTuGBq8QXyCI,AfLeUgNYBlcWy3wcSYu6S1G08hv3KyPvxKoD82wl-XDmoP...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJbzYnQte8woARJaqqFVpKeNo&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

###
df20 = pd.DataFrame(df_dict)
df20.head()

,Place ID,Photo ID
0,ChIJbzYnQte8woARJaqqFVpKeNo,AfLeUgNw9dZ6sGLCtayn83a4SPnYPICzEGI3TmVe5hSp4p...
1,ChIJbzYnQte8woARJaqqFVpKeNo,AfLeUgM0P-tzkIwCXpLqrm0uSBYVp1KeqUHRNZwd-1yQwD...
2,ChIJbzYnQte8woARJaqqFVpKeNo,AfLeUgNnFPTF3tHYCS_b7Ad13NNSxUhsxOKIGsT3iHNRTa...
3,ChIJbzYnQte8woARJaqqFVpKeNo,AfLeUgNIIoTqe_niTkp4IPiqADg7vOH1ofPbNdKluvToAs...
4,ChIJbzYnQte8woARJaqqFVpKeNo,AfLeUgNg-yVQK9PUIjVjFL2iNPYALY7EM45xET1pC-xyK5...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJY4yAluLHwoAR7y--92aDHbQ&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

###
df21 = pd.DataFrame(df_dict)
df21.head()

,Place ID,Photo ID
0,ChIJY4yAluLHwoAR7y--92aDHbQ,AfLeUgPqlMleiZS9Pl0iycVDs2fR40VnTKFgyiCmp0HCiN...
1,ChIJY4yAluLHwoAR7y--92aDHbQ,AfLeUgPlAprLJvDZQ8vIHD8vzfA5EPBb8wa8Zzu1iAAPtE...
2,ChIJY4yAluLHwoAR7y--92aDHbQ,AfLeUgNPUXfPQK2teL900-8jYHCxAHH5DAdiDZPt4AVoFZ...
3,ChIJY4yAluLHwoAR7y--92aDHbQ,AfLeUgOvoUiA0ZumeNWH6IyZq1-d6vKYNWu0UjyAdvI87_...
4,ChIJY4yAluLHwoAR7y--92aDHbQ,AfLeUgPT8ZpfsPDqC14t6ofzq2rlufB8BDRgOeGg4J9iz7...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJB_8Iy1C_woARO-B5t-OFmpM&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

df22 = pd.DataFrame(df_dict)
df22.head()

,Place ID,Photo ID
0,ChIJB_8Iy1C_woARO-B5t-OFmpM,AfLeUgN2ii8kh_2H2FbGw2T8pxZ2O7Vt_3jx76fAj6WSKo...
1,ChIJB_8Iy1C_woARO-B5t-OFmpM,AfLeUgNvobK-hxvHhbXWUvjFYcJxAAHpcJEbqnVPHeQPew...
2,ChIJB_8Iy1C_woARO-B5t-OFmpM,AfLeUgO_JCFVlfks1xNeA3qN5ARBAHmdyEWxKJ3qOjzLga...
3,ChIJB_8Iy1C_woARO-B5t-OFmpM,AfLeUgMlI_zuv4T7d7pOwtgZLTupRYT-F-N_MSihnVrAJI...
4,ChIJB_8Iy1C_woARO-B5t-OFmpM,AfLeUgODgf_mKGjx0f4dSr4Msyny5OJHS_i0r6_1vo56ut...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJF5-xKVnGwoARobBf9Z2okrM&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

###
df23 = pd.DataFrame(df_dict)
df23.head()

,Place ID,Photo ID
0,ChIJF5-xKVnGwoARobBf9Z2okrM,AfLeUgNS7pWYt47CMF51qU0NArpEroh3PFMbLL_L435RN6...
1,ChIJF5-xKVnGwoARobBf9Z2okrM,AfLeUgPQxt8uuc-wCohdwdt-jGNhyO7XLP3fGJrZGErkrM...
2,ChIJF5-xKVnGwoARobBf9Z2okrM,AfLeUgO-NXq4FypE52yPB4a--EV0AqRFEgf1LRFT2kUVRR...
3,ChIJF5-xKVnGwoARobBf9Z2okrM,AfLeUgPSC7J_7LelIG-OEUVPaY0XGivNowONDMQr-E5VHP...
4,ChIJF5-xKVnGwoARobBf9Z2okrM,AfLeUgM6_i-mf35okKNgDru0gsKJu4Y0b6vsZS0VG1sB_M...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJEWvw-dLBwoARkYj5myw6LmY&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

###
df24 = pd.DataFrame(df_dict)
df24.head()

,Place ID,Photo ID
0,ChIJEWvw-dLBwoARkYj5myw6LmY,AfLeUgMw-cyeWR7_-A4S71DXs5kNUMEI24yQYcAAzko1Nd...
1,ChIJEWvw-dLBwoARkYj5myw6LmY,AfLeUgPOUaawqTRYRkkrqbmKsx5LO8dbOiowkb2xUn9Gxp...
2,ChIJEWvw-dLBwoARkYj5myw6LmY,AfLeUgNPI7G1jH5Fkp9qMyLN_L2_YoPAugFKJOQnYFSeFn...
3,ChIJEWvw-dLBwoARkYj5myw6LmY,AfLeUgOGhKQTHLbyfbSpir4RO3S19pDK-ZS6Zf8z6eSm_K...
4,ChIJEWvw-dLBwoARkYj5myw6LmY,AfLeUgOJZ72yJbUIKl2Jn0qu9EHR5zCrFyDLjOsPbYpGJ6...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJteZy8jzJwoARldQote7Uc1k&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

###
df25 = pd.DataFrame(df_dict)
df25.head()

,Place ID,Photo ID
0,ChIJteZy8jzJwoARldQote7Uc1k,AfLeUgOnMh49XkcOsqyWCRbgP3ellw4U2TTjneeGT9lpTJ...
1,ChIJteZy8jzJwoARldQote7Uc1k,AfLeUgN8HhRU-kVSUra750i1MKnCQybDv26LnJ8-7361k0...
2,ChIJteZy8jzJwoARldQote7Uc1k,AfLeUgOAGjtxz-qSc25ovACiZMyuUWeXrX23DCtjpYYcGY...
3,ChIJteZy8jzJwoARldQote7Uc1k,AfLeUgNz2I_kkBlviZFL9AHZsL7sdRNUZSxLIRloExjLgx...
4,ChIJteZy8jzJwoARldQote7Uc1k,AfLeUgPz0KqjHXECC77xqJKH0HQNW5JfPhBq5VAMY4dYAD...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJ7UPWdzXGwoARv3xPWAYT0ok&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

###
df26 = pd.DataFrame(df_dict)
df26.head()

,Place ID,Photo ID
0,ChIJ7UPWdzXGwoARv3xPWAYT0ok,AfLeUgMEI7EUPyGfO4iodveubrLtJ8JAqnNv1NYykB_Njf...
1,ChIJ7UPWdzXGwoARv3xPWAYT0ok,AfLeUgP84pw5DtR0HwRNT1cnC5CB21CGyCxyQWTOhKkZ6Y...
2,ChIJ7UPWdzXGwoARv3xPWAYT0ok,AfLeUgOcz1g2yGbqk4CagVqVAlSds-_Esb8bmUSRIJlanc...
3,ChIJ7UPWdzXGwoARv3xPWAYT0ok,AfLeUgNppmldd2mrwHa-3UmNmAeDJFNX4s8DhSt0SZOYY1...
4,ChIJ7UPWdzXGwoARv3xPWAYT0ok,AfLeUgMir42DKM61ZrXF_K9qs0vETCLDYlmQ8cT3q0EQp4...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJR4OR2Gm5woARYeNiaa3p4zs&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

###
df27 = pd.DataFrame(df_dict)
df27.head()

,Place ID,Photo ID
0,ChIJR4OR2Gm5woARYeNiaa3p4zs,AfLeUgOaz8IiCB_lX7KmTxNwedP91USN5CU0zNxoiAiwcN...
1,ChIJR4OR2Gm5woARYeNiaa3p4zs,AfLeUgNB8tPr6beMLPb7_sD-SYHDEBntsHHsv2QxDy5lh0...
2,ChIJR4OR2Gm5woARYeNiaa3p4zs,AfLeUgPdJ9ajGmp3B76d2CJH1c8PrS4sNx1IBlCm28p3lb...
3,ChIJR4OR2Gm5woARYeNiaa3p4zs,AfLeUgOQbbepWcTtd_VYEauU-xNzgJWqjyPkvEkJ6cI0ad...
4,ChIJR4OR2Gm5woARYeNiaa3p4zs,AfLeUgNSsjfN2QB3tAfuBsRCi-cFJJ3RTyp16rD8cPc1wn...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJs0m6S-W5woARXqGSXVB4EYw&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

###
df28 = pd.DataFrame(df_dict)
df28.head()

,Place ID,Photo ID
0,ChIJs0m6S-W5woARXqGSXVB4EYw,AfLeUgM7HPWfc59i2TIIeMJEvHGCuQJfqcPCnuOy4pDCmr...
1,ChIJs0m6S-W5woARXqGSXVB4EYw,AfLeUgN9wNgMyGUfz8ea2_Rh7TOIJAl1EWJ3-tMU9WhBoT...
2,ChIJs0m6S-W5woARXqGSXVB4EYw,AfLeUgO7czFJ8eAtveQwwxO5i7r2r0Hy0gtIp6eil0FPLC...
3,ChIJs0m6S-W5woARXqGSXVB4EYw,AfLeUgNc3CLTCFIzfrfEScVD7uLFwcur8q8c6zS2GQQLXx...
4,ChIJs0m6S-W5woARXqGSXVB4EYw,AfLeUgPupldn9hWXOXOSRzvzTgugyiIVjmqMcIjX8qDekQ...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJidp6qa3AwoAR1ALo3QLZyj8&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

###
df29 = pd.DataFrame(df_dict)
df29.head()

,Place ID,Photo ID
0,ChIJidp6qa3AwoAR1ALo3QLZyj8,AfLeUgNmSwuNt8pWfsX2tkktJ-v9HENflvvrpyfUKChuGy...
1,ChIJidp6qa3AwoAR1ALo3QLZyj8,AfLeUgNHRn52uyhzWzXp5Q-WDhTd1yWshHQJYEZK694dKn...
2,ChIJidp6qa3AwoAR1ALo3QLZyj8,AfLeUgOoCRAwYApcSQChcfy8__nDh9nEMWXjKUhktUaxiL...
3,ChIJidp6qa3AwoAR1ALo3QLZyj8,AfLeUgNMuFTxHCC3e6OXlMa3ofbyydXUVxlXNwYH_WUECd...
4,ChIJidp6qa3AwoAR1ALo3QLZyj8,AfLeUgPu7YMU2TgC1TNvzEaQJSrBelE44rlvC2E2-9aCCQ...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJoeH4cobAwoARtbdnxFol0VU&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

###
df30 = pd.DataFrame(df_dict)
df30.head()

,Place ID,Photo ID
0,ChIJoeH4cobAwoARtbdnxFol0VU,AfLeUgOmDiihBpnXX_piUazk31k855gPfDLmOyIWZQrgAU...
1,ChIJoeH4cobAwoARtbdnxFol0VU,AfLeUgN1L7YlK8oINIiHAQtDysxsVaS20sSQaBFCV78zOz...
2,ChIJoeH4cobAwoARtbdnxFol0VU,AfLeUgPgPANEwPtuw2AylI3ahzEPf_AhLM0EI46zmsCqxN...
3,ChIJoeH4cobAwoARtbdnxFol0VU,AfLeUgN-zLAa2Yg9EImC3xj41AiToj-I-EYMmhUVFL3dNK...
4,ChIJoeH4cobAwoARtbdnxFol0VU,AfLeUgNPgnZ49qKze-DJnQejvpybMHE5iPJsVQAaFHCmVf...

In [ ]:
#Code to collect information from each lcoation

Locations = []
params = {}
endpoint_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJ_w8sTTRI3YAR_IJyQgtzDSs&fields=place_id%2Cphoto&key=AIzaSyCWupLokFzSpQxB6rEj5HJ_OkJXIFhfWV4"
res = requests.get(endpoint_url, params = params)
results =  json.loads(res.content)
Locations.extend(results['result'])

PhotoID_List =[]
LocationID_List = []

for i in range(len(results['result']['photos'])):
  PhotoID_List.append(results['result']['photos'][i]['photo_reference'])
  LocationID_List.append(results['result']['place_id'])
  df_dict = {'Place ID': LocationID_List, 'Photo ID': PhotoID_List}
import pandas as pd

###
df31 = pd.DataFrame(df_dict)
df31.head()

,Place ID,Photo ID
0,ChIJ_w8sTTRI3YAR_IJyQgtzDSs,AfLeUgOSGBx3XA2e2CzzMwB2wyA-lkHmCM1tBWYa5iuJol...
1,ChIJ_w8sTTRI3YAR_IJyQgtzDSs,AfLeUgMwayg-vQGmGzt26uexjgt3SWhkNV79To26hbjjed...
2,ChIJ_w8sTTRI3YAR_IJyQgtzDSs,AfLeUgMUA9z7Sj0qoppBPhk3ySql4prfo5pKbTclWRRJgy...
3,ChIJ_w8sTTRI3YAR_IJyQgtzDSs,AfLeUgPlQLabEf0J6QoFWLkLcOVkiyqIQKC5SB_41U-qI8...
4,ChIJ_w8sTTRI3YAR_IJyQgtzDSs,AfLeUgO2-d_BwfNRKCPEBYunE_bEsuemFqldp3r62Pw5JL...

In [ ]:
frames = [df0, df1, df2, df3,df4, df5, df6, df7,df8, df9, df10, df11,df12, df13, df14, df15,df16, df17, df18, df19, df20, df21, df22, df23, df24, df25,df26, df27, df28, df29, df30, df31]
result = pd.concat(frames)
result
#result.loc[result["Price Level"] =="None", "Price Level"] = 0
#result
#from google.colab import files
#result.to_csv('Locations(1).csv') 
#files.download('Locations(1).csv')

,Place ID,Photo ID
0,ChIJqaVeK1pJ3YARz9AXOaoNev0,AfLeUgO7K0NBh0vfLxjZ_3vnYzgjeBEZaJJ7KGULB86ptw...
1,ChIJqaVeK1pJ3YARz9AXOaoNev0,AfLeUgMQ9_rqrgwp0zbkYPK3L8Cg-dtUiCsZNTu7rYzIoJ...
2,ChIJqaVeK1pJ3YARz9AXOaoNev0,AfLeUgN4hT1mDLW_eAoJPsbf9qJRgPm4S892Pn4FQNntFS...
3,ChIJqaVeK1pJ3YARz9AXOaoNev0,AfLeUgOXBXTckS2JTwZkgs5S9kVyQ8KAVkZHNWeKivyDOl...
4,ChIJqaVeK1pJ3YARz9AXOaoNev0,AfLeUgPe5n-2PctJNmNWd0gaLT17U_Yr8F66vzguJEEKbU...
...,...,...
5,ChIJ_w8sTTRI3YAR_IJyQgtzDSs,AfLeUgOLoGQgp5QjPmjaC8PtV1KFlNOGWC07C9A_GA2x4_...
6,ChIJ_w8sTTRI3YAR_IJyQgtzDSs,AfLeUgMqkgNAUzcDMW3W-zzJU_gyofSLsgQYF03gF2Dw6M...
7,ChIJ_w8sTTRI3YAR_IJyQgtzDSs,AfLeUgMUcC5gMb-J4eXo4UUpv8xYz02E4gtXWrTKjKdkpn...
8,ChIJ_w8sTTRI3YAR_IJyQgtzDSs,AfLeUgN85iw3aGENBmKnGvRpvIBpPvqnJ4M5JsgSOgX7Hm...
9,ChIJ_w8sTTRI3YAR_IJyQgtzDSs,AfLeUgO7ndoVO50ykMG6Tk1ihZeqkv7VSAjleJvk_hV24w...

In [ ]:
from google.colab import files
result.to_csv('Photos.csv') 
files.download('Photos.csv')